### ISSUE TITLE
In-Laucher Settings Hidden

### ISSUE THREAD

**Issue by j2mb1** [RobinJ1995/DistroHopper#15]
Today I noticed that the Settings icon at the bottom of the launcher was replaced with a non-functional Trash icon. I had the top panel disabled so I was unable to access the settings. It persisted after opening/closing apps, locking/unlocking the phone, etc. A reboot seemed to fix the problem though, so it wasn't really a huge deal. I've tried to recreate it but it hasn't happened again since then so it may have just been a random glitch on my device's end. Great job btw. I'm not a huge Unity fan on desktop(xfce FTW;) but it looks really nice on my Aquos Crystal.

**Comment by RobinJ1995** [comment]
Huh? Well, that's weird. The Trash icon should only appear while dragging icons from the Launcher in order to remove them from it. Which device and Android version is this?

**Comment by j2mb1** [comment]
Sharp Aquos Crystal w/ KitKat 4.4.2

**Comment by RobinJ1995** [comment]
Odd... Version 0.5.12 of Ubuntu Launcher?

Do you have any other devices to test on? If this only happens on that specific device then it's likely that the manufacturer broke something, and I probably won't be able to do much about it.

**Comment by j2mb1** [comment]
I got it to do the same on my brother's Samsung Galaxy S3. Apparently it
happens if you push the home button while moving an app on the side
launcher (not sure how I ended up doing that originally.) I'm attaching
screenshots of both phones.

**Comment by RobinJ1995** [comment]
So you press and hold an app icon so you can start dragging it to a differen location on the screen, and while you're dragging it you press the device's home button with another finger? For me the hardware and/or on-screen controls are unresponsive while dragging something around. I'll have a look and test this on some other devices :)
