### ISSUE TITLE
Icon sizes 

### ISSUE THREAD

**Issue by JamesTobin** [RobinJ1995/DistroHopper#17]
It's a good thing you can change icon sizes in the panel, but the launcher icon sizes are way too big on my screen, can they please be made adjustable?

**Comment by TheNextLevel33** [comment]
I agree

**Comment by RobinJ1995** [comment]
Implemented :)

Released as [2.6.0](https://github.com/RobinJ1995/DistroHopper/releases/tag/2.6.0).
Will be pushing to the Google Play Store soon.

**Comment by JamesTobin** [comment]
awesome!
