### ISSUE TITLE
Replace Google trackers

### ISSUE THREAD

**Issue by IzzySoft** [RobinJ1995/DistroHopper#19]
Currently, DistroHopper uses Google Analytics (`/com/google/android/gms/analytics`), and somehow also Google Tag Manager (`/com/google/android/gms/tagmanager`) sneaked in. As the former is mainly intended for crash reports, it should be replaced by something less intrusive, e.g. [ACRA](https://github.com/acra/acra) – and the Tag Manager should be removed (if it can be figured out what draws it in).

Thanks in advance!

**Comment by RobinJ1995** [comment]
I'm slowly rolling this out as version 2.5.0 in the beta channel. Once I've confirmed that I get data coming in, I'll proceed to the stable channel.

Running an analysis on the generated app bundle, I can no longer see any `com.google.*` packages :) 
![](https://i.imgur.com/QItyBoa.png)

**Comment by IzzySoft** [comment]
Thanks @RobinJ1995! As soon as my updater grabbed that version, we will see what my scanner reports :smiley:

**Comment by RobinJ1995** [comment]
If you don't want to wait, there is also an APK file attached here: https://github.com/RobinJ1995/DistroHopper/releases/tag/2.5.0

I upload AAB (Android App Bundle) files to the Play Store, so any APK you grab from there would be device-specific (based on screen size etc).

**Comment by IzzySoft** [comment]
Uh, ahem, sorry, but:

```
DOES NOT VERIFY
ERROR: No JAR signatures
ERROR: 
repo/be.robinj.distrohopper_94.apk: 
ERROR: Old APK signature failed to verify: repo/be.robinj.distrohopper_94.apk
```

Did you sign that APK? And not forget the "older sigs" for MM and below (i.e. signed it v1+v2, and not just v2 only)?

**Comment by IzzySoft** [comment]
PS: if you cannot wait for the results of my scanners, here's a short summary: Yeeeha! :smile:

**Comment by IzzySoft** [comment]
@RobinJ1995 can you replace the unsigned APK by a signed one? My updater complains every day :scream:

**Comment by RobinJ1995** [comment]
@IzzySoft I've replaced the APK file with a V1+V2 signed APK :) https://github.com/RobinJ1995/DistroHopper/releases/tag/2.5.0

**Comment by IzzySoft** [comment]
Thanks! That was accepted by fdroidserver – and triggered a chain-reaction:

* `checkAntis` told me to remove `Tracking`
* Verifying that, I also removed `NonFreeDep` (yay, congrats! :tada: :man_dancing:)
* re-enabled auto updates as well

So now this issue is really completed – thanks again! News will show up with the next sync tomorrow. Oh: `NonFreeNet` is still left, obviously triggered by the DonationsLib depending on GMS (and PayPal). But hey, that looks waaayy better now!

**Comment by RobinJ1995** [comment]
Yeah that last one I probably can't really get rid of unless I maintain a build with and a build without it, which would be a bit of a pain... Google Play Store's policies are a bitch as always.

**Comment by IzzySoft** [comment]
It will stop working anyway in a year I'm afraid. Google will force apps in Play to use API v3, which is not FOSS. So then you have 3 (or 4) options:

* ignore that (and get your app unlisted from Play)
* switch to v3 (and get the NonFreeDep added with my repo as well as no chance to get your app into F-Droid's repo)
* switch to a different (hopefully FOSS) payment module
* kick it out altogether

If you're interested, I could check my library definitions for possible alternatives. Let me know then which payment options you'd need.

**Comment by IzzySoft** [comment]
Hi @RobinJ1995 and apologies for kicking this up again… ACRA switched to default to opt-out a while ago unless the developer does not explicitly set it to opt-in. May I ask how you've set up ACRA with DistroHopper, and if it's opt-out if there are chances to make it opt-in so the `Tracking` anti-feature can be avoided?

**Comment by IzzySoft** [comment]
Ouch, just checked your code while waiting for your reply and [found this](https://github.com/RobinJ1995/DistroHopper/blob/3b0f055e309dfc075e6ce1d58ddb3ba0a69f26d6/app/src/main/java/be/robinj/distrohopper/ExceptionHandler.java#L76):

```java
ACRA.getErrorReporter().handleSilentException(ex);
```

So you're even explicitly using the silent variant which does not ask the user. Had to raise the `Tracking` anti-feature then. Should you change this, please give me a ping and I can remove the AF again.

**Comment by IzzySoft** [comment]
@RobinJ1995 any answer to my last question? Is crash reporting opt-in now, or does it happen "behind the backs" without asking?

While here, our scanners reported

```
! repo/be.robinj.distrohopper_102.apk declares sensitive permission(s):
  android.permission.READ_EXTERNAL_STORAGE android.permission.SYSTEM_ALERT_WINDOW
! repo/be.robinj.distrohopper_102.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

Could you please clarify what the two permissions are needed/used for? Concerning `DEPENDENCY_INFO_BLOCK`, that can easily be avoided by adding a few lines to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs (for IzzyOnDroid/F-Droid)
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles (for Google Play)
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

Thanks in advance!

**Comment by IzzySoft** [comment]
PS: mind to add some screenshots to `fastlane/metadata/android/en-US/images/phoneScreenshots`? 😉

**Comment by RobinJ1995** [comment]
When ACRA_USERNAME and ACRA_PASSWORD are not set during the build, all crash reporting functionality will be disabled (rather than just not being stored like before) as of 3535e6a

**Comment by IzzySoft** [comment]
Thanks, that answers part of my question from 4 years ago. But are they set for your build? What about the other questions?

**Comment by RobinJ1995** [comment]
- Donations lib: no longer an issue, I removed it years ago
- Crash reporting: as of the next release, it's opt-out with a clearly labelled setting for it, unless you build your own APKs in which case crash reporting functionality is disabled entirely
- Screenshots: I'll need to update those at some point, they're indeed very outdated; created #87 so I (hopefully) don't forget
- Permissions: https://github.com/RobinJ1995/DistroHopper/blob/master/app/src/main/AndroidManifest.xml -- see explanation for each below
  - android.permission.INTERNET: For use by lenses ("search sources") in the dash
  - android.permission.ACCESS_NETWORK_STATE: to detect whether the device is online, for correct handling of network failures in lenses
  - android.permission.READ_EXTERNAL_STORAGE: For use by the local files lens and to calculate the dominant colour of the wallpaper (only used on Android 12 and older)
  - android.permission.READ_MEDIA_IMAGES, android.permission.READ_MEDIA_VIDEO, android.permission.READ_MEDIA_AUDIO: For use by the local files lens on Android 13 and newer
  - android.permission.WAKE_LOCK: This may be a remnant of something, I see it was added before the project was even moved from Launchpad to Github (11+ years ago) but nothing seems to actually use this anymore :) I'll investigate and remove it if it is no longer needed. #88
  - android.permission.ACCESS_HIDDEN_PROFILES to access Android profiles (only works if the user has set DistroHopper as their home screen)
  - android.permission.SYSTEM_ALERT_WINDOW: Used to display over other apps. This was initially added for the "launcher service" which made the launcher bar available with a swipe gesture from within other apps (but current versions don't actually allow enabling this feature by normal means, though the code still lives there)
  - android.permission.GET_TASKS: To show "running" indicators in the launcher for apps that are currently running (again, this is currently not actually available anywhere anymore using normal means, but code still exists)
- As for DEPENDENCY_INFO_BLOCK, this is something that makes maintenance of the project easier to me, so given my limited time for this project I'm going to leave this enabled for the main releases, since the Google Play Store is the primary distribution mechanism for this app

However; 9b33b40
I've modified the release pipeline so that a separate privacy-conscious APK will be built and attached to Github releases with suffix `-paranoia` (for future releases). This separate release removes crash reporting and disables the DEPENDENCY_INFO_BLOCK.
I'm releasing this with the disclaimer that I'm making this available on a best-effort basis, and if it ever gets in the way and takes away time that I would otherwise spend working on features and bugfixes I'll likely just disable it; but for now it's there and I hope it addresses your concerns :)

**Comment by IzzySoft** [comment]
Thanks! I've added explanations for INTERNET, ACCESS_NETWORK_STATE, and READ_EXTERNAL_STORAGE for now. Regarding SYSTEM_ALERT_WINDOW and GET_TASKS: maybe remove them as well if they are not used? The MEDIA permissions are not yet present with 2.7.0 it seems, so I cannot yet add them.

As for DEPENDENCY_INFO_BLOCK and Play Store: what do you ship there? I guess you only upload the AAB to Play, but not the APK? If that's correct, just add `includeInApk = false` and skip `includeInBundle = false` (or set the latter to `true`) – problem solved: we only pick the APK (then without that blob), Goog just gets the AAB (with the blob). Ah, I see that's what you basically [already did](https://github.com/RobinJ1995/DistroHopper/blob/522774ca6fcb61108e02817a41995d349ba9ebfe/app/build.gradle#L67) for the `paranoia` variant 🤗 

> This separate release removes crash reporting and disables the DEPENDENCY_INFO_BLOCK.

Ah! OK, if it also removes crash reporting (or makes it opt-in), it indeed makes sense for us to pick up the separate flavor. So the APK file name will then be `app-release-paranoia.apk`? Then I'd set that already now, so the correct APK is being picked up once the release arrives.

As we wanted to try RB again when v3.0.0 is out (see: #34), we'd build that one by passing `-PparanoiaBuild=true` to gradlew, correct?

**Comment by RobinJ1995** [comment]
The filename will be `DistroHopper-$RELEASE_VERSION-paranoia.apk` (e.g. `DistroHopper-v3.0.0-paranoia.apk`) :) 
Yup, `-PparanoiaBuild=true` should do it.

**Comment by RobinJ1995** [comment]
@IzzySoft See https://github.com/RobinJ1995/DistroHopper/releases/tag/v3.0.0e :) 
This is a test release, not a stable release, so please don't actually release this. But that's what it'll look like :)

**Comment by IzzySoft** [comment]
Thanks! An no worries: you've properly marked it "pre-release", so our updaters (for the repo and for our builders) will ignore it.

While I'm here: once you've added some screenshots to your fastlane tree, please let me know. We'd need to toggle fetching them at our end.

**Comment by RobinJ1995** [comment]
@IzzySoft do you want to check if this is all good? https://github.com/RobinJ1995/DistroHopper/tree/master/fastlane/screenshots
Is there anything I need to/can define to pick the order they are shown in, or is this it? :)

**Comment by IzzySoft** [comment]
You can prefix the filles with numerics, like `01-foobar.png`, `02-ahoo.png` – they'll be ordered alpha-numerical. And don't forget to put the folder into the correct location then: `fastlane/metadata/android/en-US/images/phoneScreenshots` 😉

**Comment by RobinJ1995** [comment]
> You can prefix the filles with numerics, like `01-foobar.png`, `02-ahoo.png` – they'll be ordered alpha-numerical. And don't forget to put the folder into the correct location then: `fastlane/metadata/android/en-US/images/phoneScreenshots` 😉

done :)

**Comment by IzzySoft** [comment]
Enabled here already, so they should be pulled along with the next release 🤗

**Comment by RobinJ1995** [comment]
> Enabled here already, so they should be pulled along with the next release 🤗

I released v3.0.0 earlier today if you want to test if pulling the paranoia build works :)

**Comment by IzzySoft** [comment]
Fastlane is pulled from the release tag, so the screenshots won't come along (as you moved them to the correct place with a later commit).

Oh, I also see DistroHopper is on the monthly update track (was put there in 2021, when there was no release for more than a year, and never put back to the daily track. After 2.6.1, it took more than 4 years for the next release… I can manually trigger an update if you wish – or shall we wait for one covering the screenshots? And are there more releases planned, so it makes sense to move the app back to the daily track?

**Comment by RobinJ1995** [comment]
I don't mind, the old screenshots are mostly still accurate other than the phone screen sizes of now vs 10 years ago :) So if they only update on the next release that's fine

Development of this has always been pretty on-and-off so no guarantees (it's a hobby project after all 😄), but there will at least be a v3.0.1 release coming soon to fix a translations bug

**Comment by IzzySoft** [comment]
OK, so I've pulled the trigger. Our updater refused:

```
! be.robinj.distrohopper_v3.0.0.apk has AntiFeatures: Tracking
- Checking the app's AndroidManifest.xml …
! repo/be.robinj.distrohopper_111.apk declares intent-filter(s): android.accessibilityservice.AccessibilityService
! repo/be.robinj.distrohopper_111.apk declares sensitive permission(s): android.permission.SYSTEM_ALERT_WINDOW
! repo/be.robinj.distrohopper_111.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
! be.robinj.distrohopper_v3.0.0.apk failed ManifestCheck; needs to be quarantined
```

The blocker would be `android.accessibilityservice.AccessibilityService` – which wasn't there before. What was it added for? `android.permission.SYSTEM_ALERT_WINDOW` was already there with 2.7.0, but also would need an explanation.

As for `DEPENDENCY_INFO_BLOCK`: please add a few lines to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs (for IzzyOnDroid/F-Droid)
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles (for Google Play)
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. in our documentation on [Signing Block Checks](https://izzyondroid.org/about/security/ApkScans/#signingblock-checks) at our website, and in our blog article [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

**Comment by RobinJ1995** [comment]
@IzzySoft see our previous convo about this :) `-paranoia` build has no crash reporting and has dependency info disabled, system alert window is legacy functionality that is currently not exposed (but can technically still be enabled by long term users), accessibility service permission is explained in the app description (including in the fastlane metadata)

**Comment by IzzySoft** [comment]
> `-paranoia` build has no crash reporting

```
Offending libraries:
--------------------
* ACRA (/org/acra): Tracking

1 offending library found.
```

Sorry, but this is reported for the `-paranoia` APK. So what does ACRA do in that build?

> and has dependency info disabled

This I can confirm, thanks!

> system alert window is legacy functionality that is currently not exposed

But what is it used for? We need an explanation for adding it to the allow list.

**Comment by RobinJ1995** [comment]
@IzzySoft https://github.com/RobinJ1995/DistroHopper/issues/19#issuecomment-4991318369
ACRA is still present but disabled on the paranoia build, I won't go down the rabbit hole of conditional dependency inclusion, a sterile implementation is good enough.

**Comment by IzzySoft** [comment]
OK, putting ACRA to the allow-list then (and a comment on why to our notes). Please ensure it stays disabled then with the build we fetch. Remains the explanation we can put for `SYSTEM_ALERT_WINDOW`.

**Comment by RobinJ1995** [comment]
> https://github.com/RobinJ1995/DistroHopper/issues/19#issuecomment-4991318369
>       * android.permission.SYSTEM_ALERT_WINDOW: Used to display over other apps. This was initially added for the "launcher service" which made the launcher bar available with a swipe gesture from within other apps (but current versions don't actually allow enabling this feature by normal means, though the code still lives there)

**Comment by IzzySoft** [comment]
```yaml
android.permission.SYSTEM_ALERT_WINDOW: initially added to make the launcher bar available with a swipe gesture (currently disabled)
```

Would that fit? It would also (in a way) also cover why the permission is still there despite being unused ("_currently_ disabled" sounds a bit like temporarily – not sure if you plan to activate that code again, or remove code + permission one day).

**Comment by RobinJ1995** [comment]
> android.permission.SYSTEM_ALERT_WINDOW: initially added to make the launcher bar available with a swipe gesture (currently disabled)
> Would that fit?

Yeah, accurate 

> It would also (in a way) also cover why the permission is still there despite being unused ("_currently_ disabled" sounds a bit like temporarily – not sure if you plan to activate that code again, or remove code + permission one day).

No idea either 😄 currently it's only there for people who still have it enabled from old versions

**Comment by IzzySoft** [comment]
Thanks! All set then. Please let me know should things change again. Or when we shout put DistroHopper back on the daily track (updates for it are currently checked monthly, as there were rather bigger intervals between them).
