### ISSUE TITLE
No Wiki Page

### ISSUE THREAD

**Issue by Linux4Life531** [RobinJ1995/DistroHopper#20]
There is no wiki page for this project. I will give it a go.

**Comment by Linux4Life531** [comment]
I have attampted to write a wiki page for it. Feel free to update it and make it better.

**Comment by RobinJ1995** [comment]
There is a (not very well advertised, fairly outdated) [website](https://distrohopper.robinj.be/) for this project. I've copied the text that was on the website into the wiki for now :)
