### ISSUE TITLE
Problem with keyboard and launcher

### ISSUE THREAD

**Issue by SamBurgos** [RobinJ1995/DistroHopper#5]
When I try to write a message and my phone is in portrait, the keys of the left side blocked and you can't use them or is very hard to type using those. I don't have that problem putting the phone in landscape

Steps to reproduce:
1) activate the launcher
2) try to use any application that activates the keyboard (message, Telegram, contacts, etc.)
3) If you try to use the left-sided keys (Q, A, Z, shift and change to number/character) when you type is too hard to use it and is like the launcher is "over" the keyboard although you can't see it

I use an LG-e425g phone and is the only one that I can reproduce the bug, maybe you can try with other brand as well. Sorry if you can't understand me at all, English is not my main language

**Comment by RobinJ1995** [comment]
This feature has been removed (or at least hidden) until I can find a way (and the time to) implement it in a better way. Closing this for now.
